### ISSUE TITLE
Check Critter Crawler mod compatibility

### ISSUE THREAD

**Issue by jarosm** [jarosm/KSP-BonVoyage#19]
Mod is using KSPWheel, but there is probably issue with wheel stress, because BV reports, that wheels are in the air.

**Comment by etmoonshade** [comment]
For what it's worth, I'm seeing a similar issue to what (seemingly) spawned this report from the forum thread - all my KSPWheel wheels are showing as not-landed, though I'm in 1.10.

I'm using up-scaled KSPWheel tracks (the RBI Mole Track from Kerbal Foundries Continued, specifically) and I can't seem to get BV to recognize that they're touching the ground. I've got all wheel damage disabled.

Using normal-scale tracks and normal-scale large wheels gives the same issue.

Using stock RoveMax wheels allows me to use BV as expected.

It's possible that KSPWheel changed since the last time it was looked at? I know it went through some sort of overhaul/change of hands/etc. somewhere around KSP 1.8...

(quick edit: All these issues were seen and tested on a 21t "rover". I'm having similar issues on my 1000t "rover" as well, though for obvious reasons no amount of stock wheels are going to let me successfully test THAT one. In both cases, I could observe that the tracks were not at full compression. Tweaking the springs to allow the tracks to "bottom out" had no effect.)

**Comment by jarosm** [comment]
Critter crawler compatibility added.

Not relevant to @etmoonshade comment. The update is compatible with the latest version of Kerbal Foundries.
