### ISSUE TITLE
Enabling rotation causes rover to explode on scene focus

### ISSUE THREAD

**Issue by n2qzshce** [jarosm/KSP-BonVoyage#45]
When "set rotation" is selected, and I switch to an active rover, the rover will fall apart. Since the vehicle has to be controlled (e.g. not from tracking station), there's no way to move the rover to another position for another attempt.

As a workaround, I disabled the rotation set, but the vehicle is in freefall when I switch to the scene and hits the ground hard.

Would there be any way to implement a landing set system like KRASH or HyperEdit?
https://github.com/linuxgurugamer/KRASH
https://github.com/Ezriilc/HyperEdit

Steps to reproduce:
1. Create a new rover and launch from the SPH
2. Set a rover destination (been using ~5km north for testing)
3. Make sure "Disable rotation" is disabled (e.g. rotation enabled)
4. Switch away from scene, warp ahead ~10m
5. Re-focus vehicle.

Currently using KSP 1.12.3.3173 and Bon Voyage 1.4.1

**Comment by jarosm** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/169206-131-18x-worldstabilizer-bugfix-for-vessels-bouncing-on-scene-load/

Rotation is automatically disabled, if you are using World Stabilizer.

**Comment by n2qzshce** [comment]
@jarosm If a certain extension is required to make your extension serve a chance of working, you should mark it as a hard dependency.
I understand vectors are challenging, you've refused to fix bugs related to positioning issues before. This mod is a nice attempt, I look forward to trying it again when it's done.

**Comment by jarosm** [comment]
@n2qzshce BV uses part of the code of World Stabilizer and this is enough in the most situations. You can try to set height offset above the ground, if the rover is to high. If stabilizing function in BV doesn't work, usually because there is an issue with height information from the game itself (the best results are with the best terrain resolution) or because a rover is to long and clips to the terrain, then you can use World Stabilizer. It is not a hard dependency and I will not implemement all functions of WS into BV, because World stabillizer resolves issues with flying vessels after scene switch . Also be aware, that rotation depends on the orientation of the root part. You can set the orientation vector manually, if your rover ends upside down or on side and then clips to terrain. You must sometimes experiment with this setting, because every rover design is unique and I can't predict them all.

**Comment by n2qzshce** [comment]
Quaternions are a pain the butt, definitely, but you might be interested in seeing how HyperEdit handles it. They have a "force up" option that seems to work with a fair degree of success.
